### ISSUE TITLE
Tags sometimes cannot be found on client

### ISSUE THREAD

**Issue by TropheusJ** [TropheusJ/stonecutter-recipe-tags#1]
I have no idea why this happens. Maybe a FAPI bug? Maybe my fault? I don't know.
- Only happens with dedicated servers
- Seemingly triggered completely at random
- Tags are not visible from the tag manager, but are indeed on the client. Can be confirmed through creative menu search.

**Comment by TobiPeterG** [comment]
for me, this happens all the times, not just sometimes (at elast I haven't had a case where it didn't happen yet)

**Comment by TropheusJ** [comment]
we *might* have found a cause. If you connect to a singleplayer world first, and then the server, does that fix it for you?

**Comment by TobiPeterG** [comment]
Just tried it (at least once) and it fixed it

**Comment by TropheusJ** [comment]
@TobiPeterG Inside this zip is a custom version. Can you test this and see if it still happens? It needs to be on both your client and server.
[test_version.zip](https://github.com/TropheusJ/stonecutter-recipe-tags/files/7148842/test_version.zip)

**Comment by TobiPeterG** [comment]
> 
> 
> @TobiPeterG Inside this zip is a custom version. Can you test this and see if it still happens? It needs to be on both your client and server.
> [test_version.zip](https://github.com/TropheusJ/stonecutter-recipe-tags/files/7148842/test_version.zip)

I added the jar to my mods folder, unfortunately still doesn't work for me without playing singleplayer first

**Comment by TropheusJ** [comment]
did you put the jar on both the client and the server? and can you send the the client log file?

**Comment by TobiPeterG** [comment]
> did you put the jar on both the client and the server? and can you send the the client log file?

Yes, I put it on server and client, I'll send a log file asap, but I'm not home atm until Wednesday, so I can send it you just then

**Comment by Siuolplex** [comment]
With Pepper's latest commits, would this bug be fixed?

**Comment by TropheusJ** [comment]
Ideally, needs to be tested more

**Comment by Cart3r1234** [comment]
I might be able to do some testing in a few hours

**Comment by TobiPeterG** [comment]
I tested it with the latest commits, it works now on my server, without having to play a singleplayer world first! :)

**Comment by triphora** [comment]
dis can be closed now \:pineapple\:

**Comment by TropheusJ** [comment]
h
